apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  labels:
    app: nextjs
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nextjs
  template:
    metadata:
      labels:
        app: nextjs
    spec:
      serviceAccountName: frontend-sa
      volumes:
        - name: frontend-secrets
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: "frontend-secrets"
      containers:
        - name: nextjs
          image: 851725173181.dkr.ecr.us-east-2.amazonaws.com/odyssey-dev-frontend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          volumeMounts:
            - name: frontend-secrets
              mountPath: "/mnt/secrets"
