version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "weekly"
    target-branch: "develop"
    labels:
      - "dependencies"
    commit-message:
      prefix: "improvement"
    open-pull-requests-limit: 10

  - package-ecosystem: "npm"
    directory: "/backend"
    schedule:
      interval: "weekly"
    target-branch: "develop"
    labels:
      - "dependencies"
    commit-message:
      prefix: "improvement"
    open-pull-requests-limit: 10
