services:
  strapi:
    container_name: strapi
    build: 
      context: ./backend
      dockerfile: Dockerfile
    image: strapi:latest
    restart: unless-stopped
    env_file:
      - ./backend/.env
      - ./backend/.docker.env
    volumes:
      - ./backend/config:/opt/app/config
      - ./backend/types:/opt/app/types
      - ./backend/src:/opt/app/src
      - ./backend/package.json:/opt/package.json
      - ./backend/yarn.lock:/opt/yarn.lock
      - ./backend/.env:/opt/app/.env
      - ./backend/public/uploads:/opt/app/public/uploads
    ports:
      - 1337:1337
    depends_on:
      - strapiDB
    networks:
      - db
      - frontend

  strapiDB:
    container_name: strapiDB
    platform: linux/amd64 #for platform error on Apple M1 chips
    restart: unless-stopped
    env_file: ./backend/.docker.env
    image: postgres:12.0-alpine
    volumes:
      - ./initdb:/docker-entrypoint-initdb.d
      - strapi-data:/var/lib/postgresql/data/ #using a volume
    ports:
      - 5432:5432
    networks:
      - db
    


  frontend: 
    build: 
      context: ./frontend 
      dockerfile: Dockerfile
    container_name: frontend
    volumes:
      - ./frontend:/app
      - frontend_node_modules:/app/node_modules
      - frontend_cache:/app/.next
    env_file:
      - ./frontend/.env.local
      - ./frontend/.docker.env
    environment:
      - WATCHPACK_POLLING=true
    ports:
      - 3000:3000
    depends_on:
      - strapi
    networks:
      - frontend
    

volumes:
  strapi-data:
  frontend_node_modules:
  frontend_cache:

networks:
  frontend:
    driver: bridge
  db:
    driver: bridge

