services:
  strapi:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      - HOST=0.0.0.0
      - PORT=1337
      - DATABASE_CLIENT=postgres
      - DATABASE_HOST=strapiDB
      - DATABASE_PORT=5432
      - DATABASE_SSL=false
      - AWS_S3_REGION=${AWS_S3_REGION}
      - AWS_S3_ENDPOINT=${AWS_S3_ENDPOINT}
      - AWS_S3_BUCKET=${AWS_S3_BUCKET}
      - AWS_CDN_URL=${AWS_CDN_URL}
      - AWS_CDN_ROOT_PATH=${AWS_CDN_ROOT_PATH}
    depends_on:
      - strapiDB
    networks:
      - db
      - frontend

  strapiDB:
    platform: linux/amd64
    restart: unless-stopped
    image: postgres:12.0-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - strapi-data:/var/lib/postgresql/data/
    networks:
      - db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    environment:
      - NEXT_PUBLIC_APP_ENV=production
      - APP_URL=${APP_URL}
      - STRAPI_API_URL=http://strapi:1337
      - NEXT_PUBLIC_STRAPI_API_URL=${NEXT_PUBLIC_STRAPI_API_URL}
      - AZURE_AD_CLIENT_ID=${AZURE_AD_CLIENT_ID}
      - AZURE_AD_TENANT_ID=${AZURE_AD_TENANT_ID}
      - GITHUB_CLIENT_ID=${GITHUB_CLIENT_ID}
      - NEXT_PUBLIC_POSTHOG_KEY=${NEXT_PUBLIC_POSTHOG_KEY}
      - NEXT_PUBLIC_POSTHOG_HOST=${NEXT_PUBLIC_POSTHOG_HOST}
      - POSTHOG_PROJECT_ID=${POSTHOG_PROJECT_ID}
      - AWS_REGION=${AWS_REGION}
      - AWS_S3_BUCKET_NAME=${AWS_S3_BUCKET_NAME}
      - AWS_S3_BUCKET_ROOT=${AWS_S3_BUCKET_ROOT}
      - AWS_S3_BUCKET_URL=${AWS_S3_BUCKET_URL}
      - AWS_CDN_URL=${AWS_CDN_URL}
    depends_on:
      - strapi
      - piston
    networks:
      - frontend

  piston:
    image: ghcr.io/engineer-man/piston:latest
    restart: unless-stopped
    privileged: true
    volumes:
      - piston-data:/piston
    networks:
      - frontend

volumes:
  strapi-data:
  piston-data:

networks:
  frontend:
    driver: bridge
  db:
    driver: bridge
