name: Build frontend and backend

on: 
  push:
    branches:
      - main
      - develop
    
  pull_request:
    branches:
      - main
      - develop
      - 'feature/**'

jobs:
  frontend-build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: 'arn:aws:iam::851725173181:role/aws-reserved/sso.amazonaws.com/AWSReservedSSO_Odyssey-FullAdmin_a1c76a0edf21210a'
          aws-region: us-east-2 

      - name: Get PostHog Key from Secrets Manager
        id: posthog_secret
        run: |
            # Fetch the entire JSON secret
            SECRET_JSON=$(aws secretsmanager get-secret-value --secret-id 'arn:aws:secretsmanager:us-east-2:851725173181:secret:odyssey/dev/frontend-1ZWCId' --query SecretString --output text)
            POSTHOG_KEY=$(echo $SECRET_JSON | jq -r .NEXT_PUBLIC_POSTHOG_KEY)
            echo "::add-mask::$POSTHOG_KEY" # Mask the secret in logs
            echo "POSTHOG_KEY=$POSTHOG_KEY" >> $GITHUB_ENV




      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install frontend dependencies
        run: |
          cd ./frontend 
          npm ci 

      - name: Build frontend
        env:
          AWS_CDN_URL: ${{ secrets.AWS_CDN_URL }}
          NEXT_PUBLIC_POSTHOG_KEY: ${{ env.POSTHOG_KEY }} # Use the fetched secret
          NEXT_PUBLIC_POSTHOG_HOST: ${{ secrets.NEXT_PUBLIC_POSTHOG_HOST }}
        run: |
          cd ./frontend 
          npm run build
        
  backend-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
            node-version: '18'

      - name: Install backend dependencies
        run: |
          cd ./backend 
          npm ci

      - name: Build backend
        run: |
          cd ./backend 
          npm run build

      

     
      
      
