name: Build frontend and backend

on: 
  push:
    branches:
      - main
      - develop
      - production
    
  pull_request:
    branches:
      - main
      - develop
      - production 
      - 'feature/**'
      - 'bug/**'
      - 'improvement/**'

jobs:
  frontend-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install frontend dependencies
        run: |
          cd ./frontend 
          npm ci 

      - name: Build frontend
        env:
          AWS_CDN_URL: ${{ secrets.AWS_CDN_URL }}
          NEXT_PUBLIC_POSTHOG_KEY: ${{ secrets.NEXT_PUBLIC_POSTHOG_KEY }} 
          NEXT_PUBLIC_POSTHOG_HOST: ${{ secrets.NEXT_PUBLIC_POSTHOG_HOST }}
        run: |
          cd ./frontend 
          npm run build
        
  backend-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.14.0'

      - name: Install backend dependencies
        run: |
          cd ./backend 
          npm ci

      - name: Build backend
        run: |
          cd ./backend 
          npm run build

      

     
      
      
