name: Push Frontend Docker Image to development AWS ECR

on:
  push:
    branches:
      - 'feature/kubernetes-dev'

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION}}

      - name: Login to AWS ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build and tag Docker image
        run: |
          cd ./frontend
          docker build -t ${{ secrets.ECR_DEV_FRONTEND_REPOSITORY }}:latest -f kubernetes.Dockerfile .


      - name: Push Docker image to ECR
        run: |
          docker tag ${{ secrets.ECR_DEV_FRONTEND_REPOSITORY }}:latest ${{ steps.login-ecr.outputs.registry }}/${{ secrets.ECR_DEV_FRONTEND_REPOSITORY }}:latest
          docker push ${{ steps.login-ecr.outputs.registry }}/${{ secrets.ECR_DEV_FRONTEND_REPOSITORY }}:latest
      
      - name: Set up kubectl
        run: |
          curl -LO "https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl"
          chmod +x ./kubectl
          sudo mv ./kubectl /usr/local/bin/kubectl

      - name: Verify kubectl installation
        run: kubectl version --client

      - name: Configure kubectl
        env:
          KUBECONFIG: ${{ secrets.KUBECONFIG }}
        run: |
          mkdir -p $HOME/.kube
          echo "${{ secrets.KUBECONFIG }}" > $HOME/.kube/config

      - name: Apply Kubernetes configuration
        run: kubectl rollout restart deployment/frontend-deployment 
      
          
