name: Check pull request source branch
on:
  pull_request_target:
    types:
      - opened
      - reopened
      - synchronize
      - edited
jobs:
  check-branches:
    runs-on: blacksmith-2vcpu-ubuntu-2204
    env:
      PR_HEAD_REF: ${{ github.event.pull_request.head.ref }}
      PR_BASE_REF: ${{ github.event.pull_request.base.ref }}
    steps:
      - name: Validate branch name characters
        run: |
          if [[ ! "$PR_HEAD_REF" =~ ^[A-Za-z0-9._/-]+$ ]]; then
            echo "Branch name contains disallowed characters."
            exit 1
          fi

      - name: Check if PR to production is from develop
        if: github.event.pull_request.base.ref == 'production'
        run: |
          if [ "$PR_HEAD_REF" != "develop" ]; then
            echo "Merge requests to production are only allowed from the develop branch."
            exit 1
          fi

      - name: Check if PR to develop follows branch naming convention
        if: github.event.pull_request.base.ref == 'develop'
        run: |
          if [[ ! "$PR_HEAD_REF" =~ ^(feature/|bug/|improvement/|dependabot/) ]]; then
            echo "Pull request to develop must come from a branch beginning with 'feature/', 'bug/', 'improvement/', or 'dependabot/'."
            exit 1
          fi